# Generated by Django 3.2.9 on 2021-12-16 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211216_2038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statuslog',
            options={
                'verbose_name': 'Logging',
                'verbose_name_plural': 'Logging'
            },
        ),
        migrations.RemoveField(
            model_name='statuslog',
            name='create_datetime',
        ),
    ]
