# Generated by Django 3.2.9 on 2021-12-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211216_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuslog',
            name='ip',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
