# Generated by Django 3.2.9 on 2021-12-24 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20211224_1718'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='jobLogs',
            new_name='jobLog',
        ),
    ]
