# Generated by Django 3.2.9 on 2021-12-31 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_joblogs_joblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblog',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
